name: Publish to MCP Registry

on:
  push:
    tags: ["v*"]  # Triggers on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update server.json version
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          echo "Updating server.json to version $VERSION"
          jq --arg v "$VERSION" '.version = $v | .packages[0].version = $v' server.json > tmp.json && mv tmp.json server.json
          cat server.json

      - name: Build and publish Docker container with version tag
        run: dotnet publish MonkeyMCP/MonkeyMCP.csproj /t:PublishContainer -p ContainerRegistry=docker.io -p ContainerImageTag=${{ steps.version.outputs.VERSION }}

      - name: Build and publish Docker container with latest tag
        run: dotnet publish MonkeyMCP/MonkeyMCP.csproj /t:PublishContainer -p ContainerRegistry=docker.io -p ContainerImageTag=latest

      - name: Install MCP Publisher
        run: |
          # Download MCP Publisher using the actual release filename format
          # The docs show /latest/ but that doesn't work, so we use a specific version
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
          
          echo "Downloading mcp-publisher for ${OS}_${ARCH}"
          curl -L -f -o mcp-publisher.tar.gz \
            "https://github.com/modelcontextprotocol/registry/releases/download/v1.2.3/mcp-publisher_1.2.3_${OS}_${ARCH}.tar.gz"
          
          tar xzf mcp-publisher.tar.gz
          chmod +x mcp-publisher
          ./mcp-publisher --help

      - name: Login to MCP Registry
        run: ./mcp-publisher login github-oidc

      - name: Publish to MCP Registry
        run: ./mcp-publisher publish